<?php
declare(strict_types=1);

namespace Nette\Bridges\SecurityTracy;

use Tracy\Dumper;

?>
<div class="nette-UserPanel">
	<h1><?php if ($user->isLoggedIn()): ?>Logged in<?php else: ?>Unlogged<?php endif ?></h1>

	<?php if ($user->getIdentity()): echo Dumper::toHtml($user->getIdentity(), [Dumper::LIVE => true]); else: ?><p style="text-align:center;padding:1em 0;color:#888">No&nbsp;identity.</p><?php endif ?>
</div>
